In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
from google.colab import files

In [ ]:
files.upload()

Saving homeprices.csv to homeprices.csv


{'homeprices.csv': b'area,bedrooms,age,price\n2600,3,20,550000\n3000,4,15,565000\n3200,,18,610000\n3600,3,30,595000\n4000,5,8,760000\n4100,6,8,810000\n'}

In [ ]:
df=pd.read_csv('homeprices.csv')

In [ ]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
df.bedrooms.median()

4.0

In [ ]:
import math

In [ ]:
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [ ]:
df.bedrooms.fillna(median_bedrooms,inplace=True)

In [ ]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
lreg=linear_model.LinearRegression()

In [ ]:
lreg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [ ]:
lreg.predict([[3000,4,10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([618748.66891723])

In [ ]:
lreg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
lreg.intercept_

221323.00186540396

In [ ]:
## Excercise

In [ ]:
ex=pd.read_csv('hiring.csv')

In [ ]:
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
ex.experience.fillna('Zero',inplace=True)
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
ex['test_score(out of 10)'].fillna(ex['test_score(out of 10)'].median(),inplace=True)
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
from word2number import w2n

In [ ]:
ex.experience=ex.experience.apply(w2n.word_to_num)

In [ ]:
ex

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
lreg.fit(ex[['experience',	'test_score(out of 10)',	'interview_score(out of 10)']],ex['salary($)'])

LinearRegression()

In [ ]:
lreg.predict([[2,9,6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53205.96797671])

In [ ]:
lreg.predict([[12,10,10]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([92002.18340611])

In [ ]:
lreg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [ ]:
lreg.intercept_

17737.263464337688